//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobeTrek.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Revenue
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public decimal totalSales { get; set; }
        public int totalOrders { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public Nullable<System.DateTime> updatedAt { get; set; }
    }
}
