//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobeTrek.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tour()
        {
            this.FavoriteTours = new HashSet<FavoriteTour>();
            this.Orders = new HashSet<Order>();
            this.TourAvailabilities = new HashSet<TourAvailability>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public decimal price { get; set; }
        public Nullable<decimal> specialAdultPrice { get; set; }
        public Nullable<decimal> childPrice { get; set; }
        public Nullable<decimal> specialChildPrice { get; set; }
        public string location { get; set; }
        public int duration { get; set; }
        public Nullable<bool> isDisabled { get; set; }
        public Nullable<bool> isApproved { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<bool> deletionRequested { get; set; }   
        public int tourTypeId { get; set; }
        public int destinationId { get; set; }
        public string imageUrls { get; set; }
        public string videoUrls { get; set; }
    
        public virtual Destination Destination { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FavoriteTour> FavoriteTours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TourAvailability> TourAvailabilities { get; set; }
        public virtual TourType TourType { get; set; }
    }
}
