//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobeTrek.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourAvailability
    {
        public int id { get; set; }
        public int tourId { get; set; }
        public System.DateTime date { get; set; }
        public int availableSeats { get; set; }
    
        public virtual Tour Tour { get; set; }
    }
}
