//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobeTrek.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TravelDBEntities : DbContext
    {
        public TravelDBEntities()
            : base("name=TravelDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CustomerInfo> CustomerInfoes { get; set; }
        public virtual DbSet<Destination> Destinations { get; set; }
        public virtual DbSet<FavoriteTour> FavoriteTours { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Revenue> Revenues { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TourAvailability> TourAvailabilities { get; set; }
        public virtual DbSet<Tour> Tours { get; set; }
        public virtual DbSet<TourType> TourTypes { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
